### ISSUE TITLE
[Broadcaster] Video sometimes doesn't load

### ISSUE THREAD

**Issue by mickel8** [elixir-webrtc/apps#35]
Sometimes video on the viewer side doesn't load. I would check how we handle keyframe requests sent from the browser

**Comment by LVala** [comment]
Reason: once in a while, the ICE from our side won't connect, which seems to be caused by packet loss issues (all of the conn checks or responses for these conn checks in a span of 100-200 ms are dropped).

Adding retransmission to `ex_ice` (https://github.com/elixir-webrtc/ex_ice/pull/56) seems to fix the problem.
